### ISSUE TITLE
Todo list to V1

### ISSUE THREAD

**Issue by kindlyfire** [kindlyfire/subtekstoj.net#1]
This issue should list everything that has to be implemented and figured out before I can launch the first version of the website. If any other features are proposed I'll add them here.

- [ ] Create a REST API for all resources
- [ ] Allow members to register and login
- [ ] Allow members to edit their account
- [ ] Allow members to create and edit pages (one page per movie/season of a series)
- [ ] Allow members to upload subtitles to a page (in case of a season of a series, one subtitle file can be uploaded per episode)
- [ ] Allow subtitles to be downloaded by anyone
- [ ] Create a search feature
- [ ] Create a Movies page (listing recently added and popular)
- [ ] Create a Series page (listing recently added and popular)
- [ ] Allow administrators to create collections (multiple movies together, or seasons of a series)

**Comment by kindlyfire** [comment]
I'm thinking development would go more quickly by not making it an SPA. It's not needed anyway. I'm going to drop React and just use Pug server-side.
